#!/usr/bin/env python3
"""Generate copperconfig.ron and pgo.ron from data/graph.json and data/costs.json.

One Copper task per callback, one connection per graph edge, and the scheduling
contract's chains, source periods and CPU set. The output is deterministic: the
same inputs always produce the same bytes, so `just gen` can be checked against
the committed files.
"""

import argparse
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
INDENT = "    "

ROOT_TYPE = "crate::tasks::AurRoot"
CALLBACK_TYPE = "crate::tasks::AurCallback"
JOIN_TYPE = "crate::tasks::AurJoin"
SINK_TYPE = "crate::tasks::AurSink"
MSG_TYPE = "crate::payload::AurMsg"

# The CopperList grid: 200Hz is 5ms, which divides the 20/30/100/1000ms root
# periods and paces the 33ms ones to within one grid step.
RATE_TARGET_HZ = 200
CPUS = [0, 1, 2, 3]
MAX_IN_FLIGHT = 4

HEADER = """// Generated by gen_config.py from data/graph.json and data/costs.json; edit those.
// The Autoware Universe replica: 86 callbacks in 11 timer-rooted sub-DAGs. Each task
// replays its own recorded execution-time sequence, indexed by `cost_index` into
// data/costs.json and by the sequence number its root stamped.
"""

CONTRACT_HEADER = """// Generated by gen_config.py from data/graph.json. The scheduling contract read by
// cu29-plan and by the logreader's pgo-profile command: the 18 deadline chains of the
// dataset, the 11 timer roots with their periods, and the CPUs a candidate may use.
"""


def load():
    graph = json.loads((HERE / "data" / "graph.json").read_text())
    costs = json.loads((HERE / "data" / "costs.json").read_text())
    return graph, costs


def task_entry(node, cost_index):
    """One RON task entry for a callback."""
    if not node["preds"]:
        task_type, extra = ROOT_TYPE, [("period_ms", int(node["period_ms"]))]
    elif not node["succs"]:
        task_type, extra = SINK_TYPE, []
    elif len(node["preds"]) > 1:
        task_type, extra = JOIN_TYPE, []
    else:
        task_type, extra = CALLBACK_TYPE, []
    lines = [f"{INDENT * 2}(", f'{INDENT * 3}id: "{node["id"]}",', f'{INDENT * 3}type: "{task_type}",']
    if task_type in (CALLBACK_TYPE, JOIN_TYPE):
        lines.append(f"{INDENT * 3}kind: stateless_task,")
    if extra:
        lines.append(f"{INDENT * 3}config: {{")
        lines.append(f'{INDENT * 4}"cost_index": {cost_index},')
        for key, value in extra:
            lines.append(f'{INDENT * 4}"{key}": {value},')
        lines.append(f"{INDENT * 3}}},")
    else:
        lines.append(f'{INDENT * 3}config: {{"cost_index": {cost_index}}},')
    lines.append(f"{INDENT * 2}),")
    return lines


def connections(graph):
    """Edges grouped by destination so each task's input tuple follows `preds`."""
    lines = []
    for node in graph["nodes"]:
        for pred in node["preds"]:
            lines += [
                f"{INDENT * 2}(",
                f'{INDENT * 3}src: "{pred}",',
                f'{INDENT * 3}dst: "{node["id"]}",',
                f'{INDENT * 3}msg: "{MSG_TYPE}",',
                f"{INDENT * 2}),",
            ]
    return lines


def render_config(graph, costs):
    order = {name: index for index, name in enumerate(costs["order"])}
    lines = [HEADER + "("]
    lines.append(f"{INDENT}runtime: (rate_target_hz: {RATE_TARGET_HZ}),")
    lines.append(f"{INDENT}tasks: [")
    for node in graph["nodes"]:
        lines += task_entry(node, order[node["id"]])
    lines.append(f"{INDENT}],")
    lines.append(f"{INDENT}cnx: [")
    lines += connections(graph)
    lines.append(f"{INDENT}],")
    lines += [
        f"{INDENT}logging: (",
        f"{INDENT * 2}slab_size_mib: 64,",
        f"{INDENT * 2}section_size_mib: 16,",
        f"{INDENT * 2}keyframe_interval: 100,",
        f"{INDENT}),",
        ")",
    ]
    return "\n".join(lines)


def render_contract(graph):
    nodes = {node["id"]: node for node in graph["nodes"]}
    lines = [CONTRACT_HEADER + "("]
    lines.append(f"{INDENT}chains: [")
    for chain in graph["chains"]:
        lines += [
            f"{INDENT * 2}(",
            f'{INDENT * 3}id: "{chain["id"]}",',
            f'{INDENT * 3}source: "{chain["root"]}",',
            f'{INDENT * 3}sink: "{chain["sink"]}",',
            f"{INDENT * 3}deadline_ms: {int(chain['deadline_ms'])},",
            f"{INDENT * 2}),",
        ]
    lines.append(f"{INDENT}],")
    lines.append(f"{INDENT}sources: [")
    for node in graph["nodes"]:
        if node["preds"]:
            continue
        lines += [
            f"{INDENT * 2}(",
            f'{INDENT * 3}task: "{node["id"]}",',
            f"{INDENT * 3}period_ms: {int(nodes[node['id']]['period_ms'])},",
            f"{INDENT * 2}),",
        ]
    lines.append(f"{INDENT}],")
    lines.append(f"{INDENT}cpus: [{', '.join(str(cpu) for cpu in CPUS)}],")
    lines.append(f"{INDENT}max_in_flight: {MAX_IN_FLIGHT},")
    lines += [
        f"{INDENT}objective: (",
        f"{INDENT * 2}kind: deadline,",
        f"{INDENT * 2}margin: 0.2,",
        f"{INDENT}),",
        ")",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the committed files differ")
    args = parser.parse_args()

    graph, costs = load()
    outputs = {
        HERE / "copperconfig.ron": render_config(graph, costs),
        HERE / "pgo.ron": render_contract(graph),
    }
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f"{path.name} is stale: run `just gen`")
        else:
            path.write_text(text)
            print(f"wrote {path.name}")


if __name__ == "__main__":
    main()
