#![no_main]
//! Fuzz the task generated by `cu_aligner::define_task!` end to end.
//!
//! This drives the real lifecycle the runtime uses: `preprocess` (which purges
//! against the robot clock) followed by `process` with two input streams whose
//! payloads and time-of-validity are attacker controlled. Sparse streams, where
//! a message arrives with a timestamp but no payload, are normal in Copper: a
//! task that had nothing to emit still ticks.

use arbitrary::Arbitrary;
use cu29::prelude::*;
use libfuzzer_sys::fuzz_target;

mod task {
    use cu29::prelude::*;
    cu_aligner::define_task!(FuzzAligner, 0 => { 8, 8, u32 }, 1 => { 8, 8, u32 });
}
use task::FuzzAligner;

#[derive(Arbitrary, Debug)]
enum FuzzTov {
    None,
    Time(u64),
    Range(u64, u64),
}

impl FuzzTov {
    fn to_tov(&self) -> Tov {
        match self {
            FuzzTov::None => Tov::None,
            FuzzTov::Time(t) => Tov::Time(CuTime::from(*t)),
            FuzzTov::Range(a, b) => Tov::Range(CuTimeRange {
                start: CuTime::from(*a),
                end: CuTime::from(*b),
            }),
        }
    }
}

#[derive(Arbitrary, Debug)]
struct Tick {
    left_payload: Option<u32>,
    left_tov: FuzzTov,
    right_payload: Option<u32>,
    right_tov: FuzzTov,
    run_preprocess: bool,
}

#[derive(Arbitrary, Debug)]
struct Scenario {
    target_alignment_window_ms: u32,
    stale_data_horizon_ms: u32,
    ticks: Vec<Tick>,
}

fuzz_target!(|scenario: Scenario| {
    if scenario.ticks.len() > 256 {
        return;
    }

    let mut config = ComponentConfig::default();
    config.set(
        "target_alignment_window_ms",
        scenario.target_alignment_window_ms,
    );
    config.set("stale_data_horizon_ms", scenario.stale_data_horizon_ms);

    let Ok(mut aligner) = FuzzAligner::new(Some(&config), ()) else {
        return;
    };
    let ctx = CuContext::new_with_clock();

    for tick in &scenario.ticks {
        if tick.run_preprocess {
            aligner.preprocess(&ctx).expect("preprocess must not fail");
        }

        let mut left = CuStampedData::<u32, CuMsgMetadata>::new(tick.left_payload);
        left.tov = tick.left_tov.to_tov();
        let mut right = CuStampedData::<u32, CuMsgMetadata>::new(tick.right_payload);
        right.tov = tick.right_tov.to_tov();

        let mut output =
            CuStampedData::<(CuArray<u32, 8>, CuArray<u32, 8>), CuMsgMetadata>::default();

        aligner
            .process(&ctx, &(&left, &right), &mut output)
            .expect("process must not fail");

        if let Some(payload) = output.payload() {
            assert!(payload.0.len() <= 8, "output array 0 overflowed");
            assert!(payload.1.len() <= 8, "output array 1 overflowed");
        }
    }
});
